[package]
name = "web_server_multi"
version = "0.1.0"
authors = ["wangyouquan <rabibit@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
